[package]
name = "error-report"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MIT OR Apache-2.0"
description = "A library to pretty-print errors"

[dependencies]

[dev-dependencies]
anyhow = "1.0.79"
